### ISSUE TITLE
Changes to roles doesn't update

### ISSUE THREAD

**Issue by AliciaPeage** [KvasirSGDevelopment/Aurora#21]
GET IT FIXED!!!!

**Comment by Luke0129** [comment]
Glem det

**Comment by sagooper** [comment]
We are working on it and well fix it in a future update

**Comment by Luke0129** [comment]
promise it will be fixed before Version 4

**Comment by Luke0129** [comment]
This is now fixed in the prerelease of v1.1.0:02, and will be added to the master branch after furthor testing.
